name: pages
on:
  push:
    branches:
      - master
    paths:
      - public/*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup cache
        id: packwiz-cache
        uses: actions/cache@v4
        with:
          path: packwiz
          key: packwiz

      - name: download packwiz
        if: steps.packwiz-cache.outputs.cache-hit != 'true'
        run: |
          curl -L -o packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip
          unzip packwiz.zip
          chmod +x packwiz

      - name: refresh packs
        run: |
          ./packwiz refresh -y --pack-file packdata/client/pack.toml --meta-folder packdata/client/mods
          ./packwiz refresh -y --pack-file packdata/server/pack.toml --meta-folder packdata/server/mods
        shell: bash

      - name: build emotes
        run: |
          for pack in emotes/*.txt; do
              pack_name=$(cut -d '/' -f 2 <<< "$pack" | cut -d '.' -f 1)
              mkdir -p temp/$pack_name/data/emojiful/recipes
              cat << EOF > temp/$pack_name/pack.mcmeta
          {
            "pack": {
              "pack_format": 6,
              "description": "Emojiful emojis!"
            }
          }
          EOF
              cat $pack | while read line; do
                  name=$(cut -d ';' -f 1 <<< "$line" | tr '[:upper:]' '[:lower:]' )
                  link=$(cut -d ';' -f 2 <<< "$line")
                  cat << EOF > temp/$pack_name/data/emojiful/recipes/$name.json
          {
            "category": "$pack_name",
            "name": "$name",
            "url": "$link",
            "type": "emojiful:emoji_recipe"
          }
          EOF
              done
              cd temp/$pack_name
              zip -r $pack_name-resource.zip .
              mv $pack_name-resource.zip ..
              cd ../..
              rm -r temp/$pack_name
              mkdir -p public/datapacks
              mv temp/$pack_name-resource.zip public/datapacks
          done
          rm -r temp
        shell: bash

      - name: get previous tag
        id: previous-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v0.0.0

      - name: clean tag
        id: clean-tag
        run: |
          tag=${{ steps.previous-tag.outputs.tag }}
          echo "tag=${tag:1}" >> $GITHUB_OUTPUT
        shell: bash

      - name: update latest button
        run: |
          sed -i "s~%LATEST_BUTTON~{% include button.html text=\"CweamCraft-${{ steps.clean-tag.outputs.tag }}.zip 📁\" link=\"https://github.com/${{ github.repository }}/releases/download/${{ steps.previous-tag.outputs.tag }}/CweamCraft-${{ steps.clean-tag.outputs.tag }}.zip\" %}~" public/download.md

      - name: copy pack data
        run: |
          mkdir -p public/packdata
          cp -r packdata public
        shell: bash

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: true
