name: pages
on:
  push:
    branches:
      - master
    paths:
      - public/*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup cache
        id: packwiz-cache
        uses: actions/cache@v4
        with:
          path: packwiz
          key: packwiz

      - name: download packwiz
        if: steps.packwiz-cache.outputs.cache-hit != 'true'
        run: |
          curl -L -o packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip
          unzip packwiz.zip
          chmod +x packwiz

      - name: build packs
        run: |
          for s in $(cat client_mods); do ./packwiz curseforge install $s -y --pack-file packdata/client/pack.toml --meta-folder packdata/client/mods; done
          for s in $(cat server_mods); do ./packwiz curseforge install $s -y --pack-file packdata/server/pack.toml --meta-folder packdata/server/mods; done
          ./packwiz refresh -y --pack-file packdata/client/pack.toml --meta-folder packdata/client/mods
          ./packwiz refresh -y --pack-file packdata/server/pack.toml --meta-folder packdata/server/mods
        shell: bash

      - name: get previous tag
        id: previous-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v0.0.0

      - name: clean tag
        id: clean-tag
        run: |
          tag=${{ steps.previous-tag.outputs.tag }}
          echo "tag=${tag:1}" >> $GITHUB_OUTPUT
        shell: bash

      - name: update latest button
        run: |
          sed -i "s~%LATEST_BUTTON~{% include button.html text=\"CweamCraft-${{ needs.check-new.outputs.clean-tag }}.zip 📁\" link=\"https://github.com/${{ github.repository }}/releases/download/${{ steps.previous-tag.outputs.tag }}/CweamCraft-${{ steps.clean-tag.outputs.tag }}.zip\" %}~" public/modpack.md

      - name: copy pack data
        run: |
          mkdir -p public/packdata
          cp -r packdata public
        shell: bash

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: true
